### ISSUE TITLE
add Liferay Frontend Support

### ISSUE THREAD

**Issue by jtydhr88** [liferay/liferay-intellij-plugin#76]
we should add the Liferay Frontend Support on the module projects similar as **Web**
<img width="893" alt="2018-08-28 6 04 13" src="https://user-images.githubusercontent.com/860985/44716492-0acd5500-aaed-11e8-9ddd-56eb42b7fbe5.png">
it should only be saw by Intellij but not for compiling.

**Comment by dmarks2** [comment]
Hello @jtydhr88 ,

to improve support for frontend Javascript libraries I would suggest to let the IntelliJ plugin add JavaScript libraries automatically. 

In IntelliJ you can already add Javascript libraries in the Settings at **Languages & Frameworks** --> **JavaScript** --> **Libraries**. If you add libraries here they will be recognized by IntelliJ, so that code completion etc. works.

So I suggest that the IntelliJ plugin should be able to detect the required libraries and add them automatically, like this:

![image](https://user-images.githubusercontent.com/10325752/44730845-2c750f00-aae2-11e8-924c-ce2656a54fda.png)

What do you think?

**Comment by jtydhr88** [comment]
Thanks @dmarks2 , I agree with you, we need to use this way

**Comment by gamerson** [comment]
Moved to JIRA project: https://issues.liferay.com/browse/INTELLIJ-1

**Comment by dmarks2** [comment]
Hey @jtydhr88, hey @gamerson,

I did a lot of research about how to implement this properly. We should automatically add the Liferay Javascript files as "libraries" (as shown above). However which files we add here depends on the Liferay version the developer is using. 

To add Javascript libraries in the IntelliJ plugin we have to create so called "ScriptingModels". Those expect that the Javascript files are available locally (e.g. inside the plugin). But I don't think it is a good idea to include all those Javascript files inside the plugin (would increase the size of the plugin by about 30 MB for each Liferay version we would like to support).

On the Liferay DEVCON 2018 Greg presented the possibility to attach the Liferay sources automatically to your IDE (Eclipse or IntelliJ). That seems to work for gradle projects only. If we get that working for Maven projects, that would be great. Maybe this can be done by adding a <dependenyManagement> section in the pom.xml and using the "import" scope to include the official BOM files. Our IntelliJ plugin then could look up this dependencyManangement section and could attach all sources to the current project.

If we have all Liferay sources attached to the project, our IntelliJ plugin could create such "ScriptingModels" and point them to the imported Liferay sources (e.g. to the com.liferay.frontend.js.aui.web module). By this the available Javascript libraries will always match exactly the configured Liferay version.

What do you think?

(Unfortunately it seems that I cannot comment on the JIRA issues with my user account there. Otherwise I would have added this as a comment in JIRA).

**Comment by jtydhr88** [comment]
hey @gamerson do you need a call to talk about this?

**Comment by jtydhr88** [comment]
@dmarks2 please feel free to open issues in github, I can help to move it to JIRA.

**Comment by jtydhr88** [comment]
hey @dmarks2 actually I think we could only support the latest version is ok instead of supporting all of exciting versions

**Comment by dmarks2** [comment]
@jtydhr88 thank you for your feedback. I think we can even do both. Our plugin could first try to find the javascript files in the project depencencies (com.liferay.frontend.js.web and com.liferay.frontend.js.aui.web). If it does not find such dependencies we could deliver the lastest (Liferay 7.1.1 GA2?) javascript files as a fallback. 

By this the developer can define a specific version of the libraries to use if they want. If they don't, we have a default library as a fallback.

I will try to implement it in that way and send a pull request.

**Comment by jtydhr88** [comment]
hey @dmarks2, thanks for interest on this implement, I'd like to see you can help to do it. But one more thing is that I may not put this support into next release(1.2.0), I'd like to have it in 1.3.0 or later.
